[mcp_servers.context7]
command = "npx"
args = [
    "-y",
    "@upstash/context7-mcp@latest",
]

[mcp_servers.magic]
command = "npx"
args = [
    "-y",
    "@21st-dev/magic@latest",
]

[mcp_servers.magic.env]
MAGIC_API_KEY = ""
